#!/bin/bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

#cursor active at boo
xsetroot -cursor_name left_ptr &
~/.fehbg &
dunst -config $HOME/.config/dunst/dunstrc &
setxkbmap -option grp:rshift_toggle,grp:toggle_switch,grp_led:scroll us,ru & 
xrandr --output eDP1 --primary --pos 0x0 --output HDMI1  --right-of eDP1
xsettingsd &
mpd &
/usr/bin/lxqt-policykit-agent &
clipit &
udiskie -t &
nm-applet &
unclutter &
#picom --config $HOME/.config/picom/picom.conf &
urxvtd -q -f -o &
thunar --daemon &
xrdb -merge ~/.Xresources &


