#! /bin/sh
$HOME/.config/bspwm/autostart &
pgrep -x sxhkd > /dev/null || sxhkd &
#$HOME/.config/polybar/launch01 &
$HOME/.config/lemonbar/lemonbar.sh &
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
if [ "$(xrandr --query | grep -c " connected")" -eq 2 ]; then
    bspc monitor eDP1  -d I II III
    bspc monitor HDMI1 -d IV V VI VII VIII IX X 
else
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width 	1
bspc config window_gap          15

bspc config active_border_color '#273238'
bspc config normal_border_color '#273238'
bspc config focused_border_color '#ffffff'
bspc config presel_feedback_color '#273238'
bspc config pointer_follows_monitor true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle true

bspc rule -a Zathura state=tiled
bspc rule -a Ario desktop='^10' state=pseudo_tiled
bspc rule -a Thunar state=pseudo_tiled rectangle=750x450+0+0
bspc rule -a Zathura     state=tiled
bspc rule -a processing-app-Base    state=floating
bspc rule -a Kitty desktop='^1' follow=on
bspc rule -a Subl3 desktop='^4'
bspc rule -a Firefox desktop='^5'
bspc rule -a Chromium desktop='^5' follow=on
bspc rule -a Qutebrowser desktop='^5' follow=on
bspc rule -a Sylpheed desktop='^7' follow=on
bspc rule -a Viber desktop='^8'
bspc rule -a Mpv desktop='^8'
bspc rule -a Spotify desktop='^6'
