#!/bin/bash

my_laptop_external_monitor=$(xrandr --query | grep 'DP2')
if [[ $my_laptop_external_monitor = *connected* ]]; then
	xrandr --output eDP1 --primary --auto 
	xrandr --output HDMI1 --auto --right-of eDP1
	./.fehbg
fi
