#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -c $HOME/.config/polybar/config01 bar -r &
polybar -c $HOME/.config/polybar/config01 bar0 -r &
#polybar -c $HOME/.config/polybar2/menu.ini menu -r &

echo "Polybar launched..."
